Milestone 2
hemant-soni-vst-au4/bookstore pull request #4
Opened 2021-01-14 18:56 UTC by hemant-soni-vst-au4

- implemented app component
- implemented booklist, book, book form component
- created reducer and action
- reducer store initialized and connected with the app

2021-01-14 20:10 UTC, wathigo requested changes
## Changes Required :o:  
Great job on this milestone.

Let's make a few changes before we proceed to the next milestone.
### REQUIRED
**src/reducers/index.js**
* It combines app-specific reducers. The combined reducers should then be passed as the first argument in `createStore()` method in `src/index.js`.

**After making the changes, submit another request for review.**

**Happy Hacking :technologist: 
Simon Wathigo.**

2021-01-14 20:10 UTC, wathigo commented on src/components/App.js
> +function App() {
Let's  make use of es6 syntax like this:
```js
const App = () => { }
```

2021-01-15 13:57 UTC, Torres-ssf requested changes
### Changes required :muscle: 
Hi @hemant-soni-vst-au4 :hand: 
Great job on this milestone so far. 
But we need to make some changes before moving on.

- [x] We need to add a descriptive README file to your repository. The current README file it's the one generated by `create-react-app`. The title is from the Bookstore but it does not have any other description about the project. Please check the instructions [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/), you can use the template to make this process easier.
![Screenshot from 2021-01-15 10-47-51](https://user-images.githubusercontent.com/30977845/104735008-d4c1b780-571f-11eb-8436-e8f6fa4e45c8.png)

Feel free to message me on Slack if you have any questions.
Happy coding :computer: 
**Sergio Torres**

2021-01-15 18:12 UTC, uche-inyama approved these changes
## Approved

### Hi there :wave: 

Go on with the next milestone.

[**note**] Some of your commit messages are not descriptive. Read through the [commit messages](https://github.com/hemant-soni-vst-au4/bookstore/tree/milestone-2) from this link there were spelling errors. Endeavor to write more descriptive commit messages.

### Have a great day :slightly_smiling_face: 

#### ``` Uchechukwu Inyama Henry ```

2021-01-15 18:15 UTC, merged